# Generated by Django 4.0.4 on 2022-04-16 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.UUIDField(primary_key=True, serialize=False)),
                ('block_data', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('block_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('signature', models.TextField()),
                ('self_verified', models.BooleanField(default=False)),
                ('verification_timestamp', models.BigIntegerField()),
                ('aes_nonce', models.TextField()),
                ('aes_auth_tag', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BlockKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('target_alias', models.CharField(max_length=255)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
    ]
