# Generated by Django 4.0.4 on 2022-04-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0003_alter_block_verification_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
