# Generated by Django 4.0.4 on 2022-05-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('block_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('block_data', models.TextField()),
                ('timestamp', models.BigIntegerField()),
                ('block_type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
                ('signature', models.TextField()),
                ('aes_nonce', models.TextField()),
                ('aes_auth_tag', models.TextField()),
                ('prev_block_id', models.CharField(max_length=255, null=True)),
                ('prev_block_hash', models.TextField(null=True)),
                ('is_committed', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BlockMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255)),
                ('signature', models.TextField()),
                ('message_type', models.CharField(choices=[('PREPREPARE', 'Preprepare'), ('PREPARE', 'Prepare'), ('COMMIT', 'Commit')], default='PREPREPARE', max_length=20)),
                ('verified_signature', models.BooleanField(default=False)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
        migrations.CreateModel(
            name='BlockKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField()),
                ('target_alias', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
        migrations.CreateModel(
            name='BlockAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
    ]
