# Generated by Django 4.0.4 on 2022-04-17 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0005_block_prev_block_hash_block_prev_block_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockchain.block')),
            ],
        ),
    ]
