# Generated by Django 4.0.4 on 2022-05-04 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auction_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('timestamp', models.BigIntegerField()),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('HOUR_AHEAD_STARTED', 'Hour Ahead Bidding Started'), ('HOUR_AHEAD_FINISHED', 'Hour Ahead Bidding Finished'), ('ADJUSTMENT_STARTED', 'Adjustment Bidding Started'), ('ADJUSTMENT_FINISHED', 'Adjustment Bidding Finished'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='CREATED', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuctionParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.auction')),
            ],
        ),
    ]
