# Generated by Django 4.0.4 on 2022-05-07 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auction_leader',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='auctionparticipant',
            name='node',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='MCPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcp', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.auction')),
            ],
        ),
        migrations.CreateModel(
            name='BidMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('units', models.FloatField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.auction')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=255)),
                ('bid_type', models.CharField(choices=[('HOUR_AHEAD', 'Hour Ahead'), ('ADJUSTMENT', 'Adjustment')], default='HOUR_AHEAD', max_length=10)),
                ('units', models.FloatField()),
                ('rate', models.FloatField()),
                ('timestamp', models.BigIntegerField()),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='peer.auction')),
            ],
        ),
    ]
