# Generated by Django 4.0.4 on 2022-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identities',
            fields=[
                ('uri', models.URLField()),
                ('alias', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('pub_key', models.TextField()),
                ('private_key', models.TextField()),
                ('is_self', models.BooleanField()),
                ('source', models.CharField(max_length=256)),
            ],
        ),
    ]
